---
- hosts: docker
  become_user: root
  become: true
  tasks:
    - name: Perform a dist-upgrade.
      apt:
        upgrade: dist
        update_cache: yes
- hosts: proxmox
  tasks:
    - name: Perform a dist-upgrade.
      apt:
        upgrade: dist
        update_cache: yes