---
- hosts: docker
  become_user: root
  become: true
  tasks:
    - name: Perform a dist-upgrade.
      apt:
        upgrade: dist
        update_cache: yes
- hosts: proxmox
  tasks:
    - name: Perform a dist-upgrade.
      apt:
        upgrade: dist
        update_cache: yes
    - name: Update Home Assistant LXC
      shell:
        cmd: pct exec 101 apt update && pct exec 101 apt upgrade